# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 7
      exclude:
        - "databricks-sdk"
        - "databricks-labs-blueprint"
        - "databricks-labs-lsql"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/go-libs"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/metascan"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/runtime-packages"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/acceptance"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/downstreams"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/llnotes"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/databricks/databricks-sdk-go"
        - "github.com/databrickslabs/sandbox/*"
    schedule:
      interval: "daily"
