"""initial_schema

Revision ID: 423f4a48143d
Revises: 
Create Date: 2026-02-10 16:06:30.849897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423f4a48143d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('manifest_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_app_name', 'apps', ['name'], unique=False)
    op.create_index('idx_app_owner', 'apps', ['owner'], unique=False)
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_collection_name', 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('server_url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('MANAGED', 'EXTERNAL', 'CUSTOM', name='mcpserverkind'), nullable=False),
    sa.Column('uc_connection', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_server_app_id', 'mcp_servers', ['app_id'], unique=False)
    op.create_index('idx_mcp_server_kind', 'mcp_servers', ['kind'], unique=False)
    op.create_index(op.f('ix_mcp_servers_id'), 'mcp_servers', ['id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mcp_server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_mcp_server_id', 'tools', ['mcp_server_id'], unique=False)
    op.create_index('idx_tool_name', 'tools', ['name'], unique=False)
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('mcp_server_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(app_id IS NOT NULL AND mcp_server_id IS NULL AND tool_id IS NULL) OR (app_id IS NULL AND mcp_server_id IS NOT NULL AND tool_id IS NULL) OR (app_id IS NULL AND mcp_server_id IS NULL AND tool_id IS NOT NULL)', name='chk_collection_item_exactly_one_ref'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collection_item_app_id', 'collection_items', ['app_id'], unique=False)
    op.create_index('idx_collection_item_collection_id', 'collection_items', ['collection_id'], unique=False)
    op.create_index('idx_collection_item_mcp_server_id', 'collection_items', ['mcp_server_id'], unique=False)
    op.create_index('idx_collection_item_tool_id', 'collection_items', ['tool_id'], unique=False)
    op.create_index(op.f('ix_collection_items_id'), 'collection_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_id'), table_name='collection_items')
    op.drop_index('idx_collection_item_tool_id', table_name='collection_items')
    op.drop_index('idx_collection_item_mcp_server_id', table_name='collection_items')
    op.drop_index('idx_collection_item_collection_id', table_name='collection_items')
    op.drop_index('idx_collection_item_app_id', table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_index('idx_tool_name', table_name='tools')
    op.drop_index('idx_tool_mcp_server_id', table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_mcp_servers_id'), table_name='mcp_servers')
    op.drop_index('idx_mcp_server_kind', table_name='mcp_servers')
    op.drop_index('idx_mcp_server_app_id', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_index('idx_collection_name', table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_index('idx_app_owner', table_name='apps')
    op.drop_index('idx_app_name', table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
