---
name: 'Databricks Labs Acceptance Suite'
description: 'Run relevant acceptance suite'
outputs:
  owner:
    description: 'Sample output'
    value: ${{ steps.invoke.outputs.sample }}

runs:
  using: 'composite'
  steps:
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Run action
      id: invoke
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash