---
name: 'Databricks Labs Acceptance Suite'
description: 'Run relevant acceptance suite'
author: Serge Smertin
inputs:
  github_token:
    description: GitHub token to use for commenting on PR
    required: true
  go-version:
    description: 'Go version'
    required: false
    default: 1.21.0
outputs:
  sample:
    description: 'Sample output'
    value: ${{ steps.invoke.outputs.sample }}

runs:
  using: 'composite'
  steps:
    # TODO: publish as docker image, eventually
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod
    
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Run action
      id: invoke
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash
