---
name: 'Databricks Labs Acceptance Suite'
description: 'Run relevant acceptance suite'
author: Serge Smertin
inputs:
  vault_uri:
    description: 'Vault URI'
    required: true
  project:
    description: 'Project Name'
    required: false
  directory:
    description: 'Working directory'
    required: false
    default: .
  slack_webhook:
    description: 'Slack Webhook'
    required: false
outputs:
  sample:
    description: 'Sample output'
    value: ${{ steps.invoke.outputs.sample }}

runs:
  using: node20
  main: shim.js