---
name: 'Databricks Labs Acceptance Suite'
description: 'Run relevant acceptance suite'
author: Serge Smertin
inputs:
  go-version:
    description: 'Go version'
    required: false
    default: 1.21.0
outputs:
  sample:
    description: 'Sample output'
    value: ${{ steps.invoke.outputs.sample }}

runs:
  using: 'composite'
  steps:
    - name: log grounds
      run: echo "::group::Preparing..."
      shell: bash
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ github.action_path }}/go.mod
    
    - name: Download Go modules
      run: go mod download
      working-directory: ${{ github.action_path }}
      shell: bash
    
    - name: log grounds
      run: echo "::endgroup::"
      shell: bash

    - name: Run action
      id: invoke
      run: go run main.go
      working-directory: ${{ github.action_path }}
      shell: bash