# Databricks notebook source
# MAGIC %md
# MAGIC # Step 5: Configure Databricks App
# MAGIC Creates/reuses the Databricks App, configures app resources (valueFrom secrets),
# MAGIC generates app.yaml, and grants the app's Service Principal Lakebase access.

# COMMAND ----------

dbutils.widgets.text("instance_name", "lakemeter-customer")
dbutils.widgets.text("db_name", "lakemeter_pricing")
dbutils.widgets.text("app_name", "lakemeter")
dbutils.widgets.text("secrets_scope", "lakemeter-secrets")
dbutils.widgets.text("claude_endpoint", "databricks-claude-opus-4-6")

instance_name = dbutils.widgets.get("instance_name")
db_name = dbutils.widgets.get("db_name")
app_name = dbutils.widgets.get("app_name")
secrets_scope = dbutils.widgets.get("secrets_scope")
claude_endpoint = dbutils.widgets.get("claude_endpoint")

print(f"Instance: {instance_name}")
print(f"Database: {db_name}")
print(f"App: {app_name}")
print(f"Secrets scope: {secrets_scope}")
print(f"Claude endpoint: {claude_endpoint}")

# COMMAND ----------

import uuid
import requests
import psycopg2
from datetime import datetime
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.apps import App

w = WorkspaceClient()
host = w.config.host.rstrip("/")
user = w.current_user.me().user_name

# COMMAND ----------

# 1. Ensure workspace secrets exist for config values
print("Setting workspace secrets...")

# lakebase-instance-name
try:
    w.secrets.put_secret(scope=secrets_scope, key="lakebase-instance-name", string_value=instance_name)
    print(f"  {secrets_scope}:lakebase-instance-name set")
except Exception as e:
    print(f"  Warning: Could not set lakebase-instance-name: {e}")

# lakebase-host, lakebase-user, lakebase-database should already exist from 02_create_database
# Verify they exist
for key in ["lakebase-host", "lakebase-user", "lakebase-database"]:
    try:
        val = dbutils.secrets.get(scope=secrets_scope, key=key)
        print(f"  {secrets_scope}:{key} exists")
    except Exception:
        print(f"  Warning: {secrets_scope}:{key} not found — may need manual setup")

# COMMAND ----------

# 2. Create app if it doesn't exist
print(f"Checking for existing app '{app_name}'...")
try:
    app_info = w.apps.get(app_name)
    print(f"App '{app_name}' already exists")
except Exception:
    print(f"Creating Databricks App '{app_name}'...")
    try:
        app_obj = App(
            name=app_name,
            description="Lakemeter — Databricks cost estimation tool",
            default_source_code_path=f"/Workspace/Users/{user}/apps/{app_name}",
        )
        w.apps.create_and_wait(app_obj)
        print(f"App '{app_name}' created")
    except Exception as e:
        print(f"Warning: Could not create app: {str(e)[:200]}")
        print("You may need to create the app manually via the Databricks UI, then re-run the installer")

# COMMAND ----------

# 3. Configure app resources (valueFrom references)
print("Configuring app resources...")

# Resource names must be <= 30 chars. Use short fixed prefixes.
resource_map = {
    "lm-lakebase-instance": ("lakebase-instance-name", "Lakebase instance name"),
    "lm-db-host": ("lakebase-host", "Database host"),
    "lm-db-user": ("lakebase-user", "Database user"),
    "lm-db-name": ("lakebase-database", "Database name"),
}

resources = []
for name, (secret_key, desc) in resource_map.items():
    resources.append({
        "name": name,
        "description": desc,
        "secret": {"scope": secrets_scope, "key": secret_key, "permission": "READ"},
    })

# Add serving endpoint resource for AI Assistant (Claude)
resources.append({
    "name": "lm-claude-endpoint",
    "description": "Claude model endpoint for AI Assistant",
    "serving_endpoint": {"name": claude_endpoint, "permission": "CAN_QUERY"},
})

headers = w.config.authenticate()
resp = requests.patch(
    f"{host}/api/2.0/apps/{app_name}",
    headers=headers,
    json={"resources": resources},
)
if resp.status_code == 200:
    print(f"App resources configured ({len(resources)} resources)")
else:
    error_msg = f"Failed to configure app resources: {resp.status_code} {resp.text[:300]}"
    print(f"ERROR: {error_msg}")
    raise RuntimeError(error_msg)

# COMMAND ----------

# 4. Generate app.yaml and write to bundle files path
print("Generating app.yaml...")

app_yaml_content = f"""# Databricks App Configuration — generated by installer
# Instance: {instance_name} | Generated: {datetime.now().isoformat()[:19]}

command:
  - "/bin/bash"
  - "-c"
  - |
    # Start FastAPI backend (frontend is pre-built into backend/static/)
    cd backend && ../.venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port ${{DATABRICKS_APP_PORT:-8000}}

env:
  # App environment
  - name: "ENVIRONMENT"
    value: "production"
  - name: "CORS_ORIGINS"
    value: ""

  # Lakebase database configuration
  - name: "LAKEBASE_INSTANCE_NAME"
    valueFrom: "lm-lakebase-instance"
  - name: "DB_HOST"
    valueFrom: "lm-db-host"
  - name: "DB_USER"
    valueFrom: "lm-db-user"
  - name: "DB_NAME"
    valueFrom: "lm-db-name"
  - name: "DB_PORT"
    value: "5432"
  - name: "DB_SSLMODE"
    value: "require"

  # AI Assistant (Claude) model serving endpoint
  - name: "CLAUDE_MODEL_ENDPOINT"
    valueFrom: "lm-claude-endpoint"
"""

import os
# Write to bundle's app_source directory so 06_deploy_app can copy it
nb_context = dbutils.notebook.entry_point.getDbutils().notebook().getContext()
nb_path = nb_context.notebookPath().get()
if not nb_path.startswith("/Workspace"):
    nb_path = "/Workspace" + nb_path
bundle_files_dir = os.path.dirname(os.path.dirname(nb_path))
app_source_dir = os.path.join(bundle_files_dir, "app_source")
app_yaml_path = os.path.join(app_source_dir, "app.yaml")

with open(app_yaml_path, "w") as f:
    f.write(app_yaml_content)
print(f"app.yaml written to {app_yaml_path}")

# Also store as task value so deploy notebook can find it
dbutils.jobs.taskValues.set(key="app_yaml_path", value=app_yaml_path)

# COMMAND ----------

# 5. Grant app Service Principal Lakebase access
print("Granting app service principal Lakebase access...")

try:
    app_info = w.apps.get(app_name)
    app_sp_id = app_info.service_principal_client_id
    if not app_sp_id:
        print("Warning: App has no service principal — Lakebase OAuth will not work")
        print("App will use password-auth fallback (lakemeter_sync_role)")
        dbutils.notebook.exit("App configured (no SP — password auth fallback)")

    # Create Lakebase role for the app's SP
    roles_url = f"{host}/api/2.0/database/instances/{instance_name}/roles"
    resp = requests.get(roles_url, headers=headers)
    existing_roles = resp.json().get("database_instance_roles", []) if resp.status_code == 200 else []
    sp_role = next((r for r in existing_roles if r["name"] == app_sp_id), None)

    if not sp_role or sp_role.get("identity_type") != "SERVICE_PRINCIPAL":
        if sp_role:
            requests.delete(f"{roles_url}/{app_sp_id}", headers=headers)
        resp = requests.post(roles_url, headers=headers, json={
            "name": app_sp_id,
            "identity_type": "SERVICE_PRINCIPAL",
            "membership_role": "DATABRICKS_SUPERUSER",
        })
        if resp.status_code == 200:
            print(f"App SP Lakebase role created ({app_sp_id[:12]}...)")
        else:
            print(f"Warning: Could not create app SP role: {resp.status_code} {resp.text[:200]}")
    else:
        print("App SP already has Lakebase role")

    # Grant SQL-level permissions
    instance = w.database.get_database_instance(instance_name)
    instance_host = instance.read_write_dns
    cred = w.database.generate_database_credential(request_id=str(uuid.uuid4()), instance_names=[instance_name])
    owner_user = w.current_user.me().user_name

    conn = psycopg2.connect(
        host=instance_host, port=5432, database=db_name,
        user=owner_user, password=cred.token, sslmode="require",
    )
    conn.autocommit = True
    cur = conn.cursor()
    cur.execute(f'GRANT CONNECT ON DATABASE {db_name} TO "{app_sp_id}"')
    cur.execute(f'GRANT USAGE ON SCHEMA lakemeter TO "{app_sp_id}"')
    cur.execute(f'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA lakemeter TO "{app_sp_id}"')
    cur.execute(f'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA lakemeter TO "{app_sp_id}"')
    cur.execute(f'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA lakemeter TO "{app_sp_id}"')
    cur.close()
    conn.close()
    print("App SP SQL permissions granted")

except Exception as e:
    print(f"Warning: Could not configure app SP Lakebase access: {e}")
    print("App will use password-auth fallback (lakemeter_sync_role)")

# COMMAND ----------

print("App configuration complete.")
dbutils.notebook.exit(f"App '{app_name}' configured with {len(resources)} resources")
