# Databricks notebook source
# MAGIC %md
# MAGIC # Step 5a: Create & Configure Databricks App
# MAGIC Creates/reuses the Databricks App, configures app resources,
# MAGIC and generates app.yaml. Runs in PARALLEL with DB provisioning.

# COMMAND ----------

import time
_start = time.time()

dbutils.widgets.text("instance_name", "lakemeter-customer")
dbutils.widgets.text("db_name", "lakemeter_pricing")
dbutils.widgets.text("app_name", "lakemeter")
dbutils.widgets.text("secrets_scope", "lakemeter-secrets")
dbutils.widgets.text("claude_endpoint", "databricks-claude-opus-4-6")

instance_name = dbutils.widgets.get("instance_name")
db_name = dbutils.widgets.get("db_name")
app_name = dbutils.widgets.get("app_name")
secrets_scope = dbutils.widgets.get("secrets_scope")
claude_endpoint = dbutils.widgets.get("claude_endpoint")

print(f"Instance: {instance_name}")
print(f"Database: {db_name}")
print(f"App: {app_name}")
print(f"Secrets scope: {secrets_scope}")
print(f"Claude endpoint: {claude_endpoint}")

# COMMAND ----------

import os
import requests
from datetime import datetime
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.apps import App

w = WorkspaceClient()
host = w.config.host.rstrip("/")
user = w.current_user.me().user_name

# COMMAND ----------

# 1. Set workspace secrets for config values
t0 = time.time()
print("Step 1: Setting workspace secrets...")

try:
    w.secrets.put_secret(scope=secrets_scope, key="lakebase-instance-name", string_value=instance_name)
    print(f"  {secrets_scope}:lakebase-instance-name set")
except Exception as e:
    print(f"  Warning: Could not set lakebase-instance-name: {e}")

print(f"  Done ({time.time() - t0:.1f}s)")

# COMMAND ----------

# 2. Create app if it doesn't exist (this is the SLOW step ~2-3 minutes)
t0 = time.time()
print(f"Step 2: Creating Databricks App '{app_name}'...")

try:
    app_info = w.apps.get(app_name)
    print(f"  App '{app_name}' already exists ({time.time() - t0:.1f}s)")
except Exception:
    print(f"  App not found, creating...")
    try:
        app_obj = App(
            name=app_name,
            description="Lakemeter — Databricks cost estimation tool",
            default_source_code_path=f"/Workspace/Users/{user}/apps/{app_name}",
        )
        w.apps.create_and_wait(app_obj)
        print(f"  App '{app_name}' created ({time.time() - t0:.1f}s)")
    except Exception as e:
        print(f"  Warning: Could not create app: {str(e)[:200]}")
        print("  You may need to create the app manually via the Databricks UI")

# COMMAND ----------

# 3. Configure app resources (valueFrom references)
t0 = time.time()
print("Step 3: Configuring app resources...")

resource_map = {
    "lm-lakebase-instance": ("lakebase-instance-name", "Lakebase instance name"),
    "lm-db-host": ("lakebase-host", "Database host"),
    "lm-db-user": ("lakebase-user", "Database user"),
    "lm-db-name": ("lakebase-database", "Database name"),
}

resources = []
for name, (secret_key, desc) in resource_map.items():
    resources.append({
        "name": name,
        "description": desc,
        "secret": {"scope": secrets_scope, "key": secret_key, "permission": "READ"},
    })

resources.append({
    "name": "lm-claude-endpoint",
    "description": "Claude model endpoint for AI Assistant",
    "serving_endpoint": {"name": claude_endpoint, "permission": "CAN_QUERY"},
})

headers = w.config.authenticate()
resp = requests.patch(
    f"{host}/api/2.0/apps/{app_name}",
    headers=headers,
    json={"resources": resources},
)
if resp.status_code == 200:
    print(f"  App resources configured ({len(resources)} resources) ({time.time() - t0:.1f}s)")
else:
    error_msg = f"Failed to configure app resources: {resp.status_code} {resp.text[:300]}"
    print(f"  ERROR: {error_msg}")
    raise RuntimeError(error_msg)

# COMMAND ----------

# 4. Generate app.yaml and write to bundle files path
t0 = time.time()
print("Step 4: Generating app.yaml...")

app_yaml_content = f"""# Databricks App Configuration — generated by installer
# Instance: {instance_name} | Generated: {datetime.now().isoformat()[:19]}

command:
  - "/bin/bash"
  - "-c"
  - |
    # Start FastAPI backend (frontend is pre-built into backend/static/)
    cd backend && ../.venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port ${{DATABRICKS_APP_PORT:-8000}}

env:
  # App environment
  - name: "ENVIRONMENT"
    value: "production"
  - name: "CORS_ORIGINS"
    value: ""

  # Lakebase database configuration
  - name: "LAKEBASE_INSTANCE_NAME"
    valueFrom: "lm-lakebase-instance"
  - name: "DB_HOST"
    valueFrom: "lm-db-host"
  - name: "DB_USER"
    valueFrom: "lm-db-user"
  - name: "DB_NAME"
    valueFrom: "lm-db-name"
  - name: "DB_PORT"
    value: "5432"
  - name: "DB_SSLMODE"
    value: "require"

  # AI Assistant (Claude) model serving endpoint
  - name: "CLAUDE_MODEL_ENDPOINT"
    valueFrom: "lm-claude-endpoint"
"""

nb_context = dbutils.notebook.entry_point.getDbutils().notebook().getContext()
nb_path = nb_context.notebookPath().get()
if not nb_path.startswith("/Workspace"):
    nb_path = "/Workspace" + nb_path
bundle_files_dir = os.path.dirname(os.path.dirname(nb_path))
app_source_dir = os.path.join(bundle_files_dir, "app_source")
app_yaml_path = os.path.join(app_source_dir, "app.yaml")

with open(app_yaml_path, "w") as f:
    f.write(app_yaml_content)
print(f"  app.yaml written to {app_yaml_path} ({time.time() - t0:.1f}s)")

dbutils.jobs.taskValues.set(key="app_yaml_path", value=app_yaml_path)

# COMMAND ----------

elapsed = time.time() - _start
print(f"\nApp creation & configuration complete ({elapsed:.1f}s)")
dbutils.notebook.exit(f"App '{app_name}' configured with {len(resources)} resources ({elapsed:.1f}s)")
