# Databricks notebook source
# MAGIC %md
# MAGIC # Step 6: Deploy Application
# MAGIC Copies app source from the DABs bundle files path to the app's workspace source path,
# MAGIC then deploys via the Databricks SDK.

# COMMAND ----------

dbutils.widgets.text("app_name", "lakemeter")

app_name = dbutils.widgets.get("app_name")
print(f"App: {app_name}")

# COMMAND ----------

import base64
import os
import time
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.workspace import ImportFormat

w = WorkspaceClient()
user = w.current_user.me().user_name

# COMMAND ----------

# Get app info to find the source code path
app_info = w.apps.get(app_name)
ws_path = app_info.default_source_code_path
if not ws_path:
    ws_path = f"/Workspace/Users/{user}/apps/{app_name}"
print(f"App workspace source path: {ws_path}")

# COMMAND ----------

# Resolve bundle files path
nb_context = dbutils.notebook.entry_point.getDbutils().notebook().getContext()
nb_path = nb_context.notebookPath().get()
if not nb_path.startswith("/Workspace"):
    nb_path = "/Workspace" + nb_path
bundle_files_dir = os.path.dirname(os.path.dirname(nb_path))
app_source_dir = os.path.join(bundle_files_dir, "app_source")

print(f"Bundle app source: {app_source_dir}")
assert os.path.isdir(app_source_dir), f"app_source directory not found at {app_source_dir}"

# Verify key files exist
for check in ["backend/app/main.py", "requirements.txt"]:
    check_path = os.path.join(app_source_dir, check)
    assert os.path.exists(check_path), f"Required file missing: {check}"

# Check for app.yaml (generated by 05_configure_app)
app_yaml_path = os.path.join(app_source_dir, "app.yaml")
if not os.path.exists(app_yaml_path):
    print("Warning: app.yaml not found in app_source — it should have been generated by 05_configure_app")

# COMMAND ----------

# Upload app source to workspace
MAX_FILE_SIZE = 9 * 1024 * 1024  # workspace import limit ~10MB
uploaded = 0
skipped = 0
created_dirs = set()

EXCLUDE_PATTERNS = ["__pycache__", ".pyc", ".csv", "manifest.json"]


def ensure_ws_dir(ws_dir_path):
    if ws_dir_path in created_dirs:
        return
    try:
        w.workspace.mkdirs(ws_dir_path)
    except Exception:
        pass
    created_dirs.add(ws_dir_path)


ensure_ws_dir(ws_path)

for root, dirs, files in os.walk(app_source_dir):
    # Skip __pycache__ directories
    dirs[:] = [d for d in dirs if d != "__pycache__"]

    for filename in sorted(files):
        filepath = os.path.join(root, filename)
        rel_path = os.path.relpath(filepath, app_source_dir)

        # Skip excluded patterns
        if any(pat in rel_path for pat in EXCLUDE_PATTERNS):
            skipped += 1
            continue

        # Skip files too large
        if os.path.getsize(filepath) > MAX_FILE_SIZE:
            print(f"  Skipping {rel_path} (>{MAX_FILE_SIZE // 1024 // 1024}MB)")
            skipped += 1
            continue

        # Ensure parent dir exists in workspace
        rel_dir = os.path.dirname(rel_path)
        if rel_dir:
            ensure_ws_dir(f"{ws_path}/{rel_dir}")

        # Upload file
        with open(filepath, "rb") as f:
            file_bytes = f.read()

        target = f"{ws_path}/{rel_path}"
        try:
            w.workspace.import_(
                path=target,
                content=base64.b64encode(file_bytes).decode("ascii"),
                format=ImportFormat.AUTO,
                overwrite=True,
            )
            uploaded += 1
        except Exception as e:
            print(f"  Upload failed for {rel_path}: {str(e)[:100]}")

print(f"Uploaded {uploaded} files to {ws_path} (skipped {skipped})")

# COMMAND ----------

# Deploy the app via REST API (SDK deploy signature varies across versions)
import requests as req

print(f"Deploying app '{app_name}'...")
host = w.config.host.rstrip("/")
headers = w.config.authenticate()
try:
    resp = req.post(
        f"{host}/api/2.0/apps/{app_name}/deployments",
        headers=headers,
        json={"source_code_path": ws_path},
    )
    if resp.status_code < 300:
        deploy_data = resp.json()
        deploy_id = deploy_data.get("deployment_id", "unknown")
        print(f"Deployment started: {deploy_id}")
    else:
        print(f"Deploy API error: {resp.status_code} {resp.text[:200]}")
        dbutils.notebook.exit(f"Deploy failed: {resp.status_code} {resp.text[:200]}")
except Exception as e:
    print(f"Error starting deployment: {e}")
    dbutils.notebook.exit(f"Deploy failed: {e}")

# COMMAND ----------

# Wait for deployment to complete
print("Waiting for deployment to complete...")
for i in range(60):  # 10 min max
    time.sleep(10)
    try:
        app_info = w.apps.get(app_name)
        pd = getattr(app_info, "pending_deployment", None)
        ad = getattr(app_info, "active_deployment", None)
        deploy = pd or ad
        if deploy:
            state = deploy.status.state.value if hasattr(deploy.status.state, "value") else str(deploy.status.state)
            if i % 3 == 0:
                print(f"  Deploy state: {state}")
            if state == "SUCCEEDED":
                print(f"\nApp deployed successfully!")
                print(f"URL: {app_info.url}")
                dbutils.notebook.exit(f"Deployed: {app_info.url}")
            if state == "FAILED":
                msg = deploy.status.message if hasattr(deploy.status, "message") else "Unknown"
                print(f"\nDeploy failed: {msg}")
                dbutils.notebook.exit(f"Deploy failed: {msg}")
    except Exception as e:
        if i % 6 == 0:
            print(f"  Checking... ({e})")

print("Warning: Timed out waiting for deployment (10 minutes)")
print("Check deployment status in the Databricks UI")
dbutils.notebook.exit("Deploy started — check UI for status")
