# The table refresh pipeline for schema dab

resources:
  pipelines:
    refresh_pipeline:
      name: ${var.resource_name_prefix}refresh_pipeline
      catalog: ${var.catalog_name}
      schema: ${var.schema_name}
      serverless: true
      libraries:
        - file:
            path: ../src/pipelines/ingestion.py
      configuration:
        filepush.volume_path: ${resources.volumes.filepush_volume.volume_path}
