name: Release downstreams

on:
  push:
    tags:
      - 'downstreams/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: downstreams/go.mod

      - name: Build
        run: /bin/bash .github/workflows/build.sh downstreams
    
      - name: Compress
        run: /bin/bash .github/workflows/compress.sh
      
      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        with:
          files: dist/*
