name: nightly-acceptance

on:
  workflow_dispatch:
    # ...

permissions:
  contents: read

jobs:
  acceptance:
    environment: tool
    runs-on: larger
    permissions:
      # Access to the integration testing infrastructure.
      id-token: write
      # Write test results to the PR.
      pull-requests: write
      # Create issues on failure.
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          go-version-file: go-libs/go.mod

      - name: Acceptance
        uses: databrickslabs/sandbox/acceptance@3313d06ce86227537b3f37f5974f7eecb2a8e59a  # acceptance/v0.4.4
        with:
          directory: go-libs
          vault_uri: ${{ secrets.VAULT_URI }}
          create_issues: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
